// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB34O8f1DsgrsXiQw0fI1fIOWWArhmwXc',
    appId: '1:1032824326223:web:a7df66a9e1c5cb7561423a',
    messagingSenderId: '1032824326223',
    projectId: 'homiq-44256',
    authDomain: 'homiq-44256.firebaseapp.com',
    storageBucket: 'homiq-44256.firebasestorage.app',
    measurementId: 'G-QP119ZVJEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXTm25AAGuVUGOiX4zsHZDHG3uPb1TLm0',
    appId: '1:1032824326223:android:fe6c5219751fb42261423a',
    messagingSenderId: '1032824326223',
    projectId: 'homiq-44256',
    storageBucket: 'homiq-44256.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT7pMVNOxwTkO4-9WgtSttB8itw9kNjko',
    appId: '1:1032824326223:ios:5ce2924f5a3afa7161423a',
    messagingSenderId: '1032824326223',
    projectId: 'homiq-44256',
    storageBucket: 'homiq-44256.firebasestorage.app',
    iosBundleId: 'com.example.homiq',
  );
}
